/**
 * Enums de domínio compartilhados entre backend e frontend.
 */

export enum PhaseStatus {
	DISABLED = 0,
	OPEN = 1,
	BLOCKED = 2,
}

/** Fase da competição conforme Football Data API. */
export enum MatchStage {
	FINAL = 'FINAL',
	SEMI_FINALS = 'SEMI_FINALS',
	THIRD_PLACE = 'THIRD_PLACE',
	QUARTER_FINALS = 'QUARTER_FINALS',
	LAST_16 = 'LAST_16',
	LAST_32 = 'LAST_32',
	LAST_64 = 'LAST_64',
	ROUND_4 = 'ROUND_4',
	ROUND_3 = 'ROUND_3',
	ROUND_2 = 'ROUND_2',
	ROUND_1 = 'ROUND_1',
	GROUP_STAGE = 'GROUP_STAGE',
	PRELIMINARY_ROUND = 'PRELIMINARY_ROUND',
	QUALIFICATION = 'QUALIFICATION',
	QUALIFICATION_ROUND_1 = 'QUALIFICATION_ROUND_1',
	QUALIFICATION_ROUND_2 = 'QUALIFICATION_ROUND_2',
	QUALIFICATION_ROUND_3 = 'QUALIFICATION_ROUND_3',
	PLAYOFF_ROUND_1 = 'PLAYOFF_ROUND_1',
	PLAYOFF_ROUND_2 = 'PLAYOFF_ROUND_2',
	PLAYOFFS = 'PLAYOFFS',
	REGULAR_SEASON = 'REGULAR_SEASON',
	CLAUSURA = 'CLAUSURA',
	APERTURA = 'APERTURA',
	CHAMPIONSHIP = 'CHAMPIONSHIP',
	RELEGATION = 'RELEGATION',
	RELEGATION_ROUND = 'RELEGATION_ROUND',
}

/** Status de partida conforme Football Data API. */
export enum MatchStatus {
	SCHEDULED = 'SCHEDULED',
	LIVE = 'LIVE',
	IN_PLAY = 'IN_PLAY',
	PAUSED = 'PAUSED',
	FINISHED = 'FINISHED',
	POSTPONED = 'POSTPONED',
	SUSPENDED = 'SUSPENDED',
	CANCELLED = 'CANCELLED',
}

/** Pontuações válidas para um palpite, conforme regra do bolão. */
export const PONTOS_VALIDOS = [0, 1, 2, 3, 5] as const
export type PontosObtidos = (typeof PONTOS_VALIDOS)[number]
