import type { TeamPayload } from '@bolao/shared'

type PtName = { name: string; short?: string }

const PT_BY_TLA: Record<string, PtName> = {
	// CONMEBOL
	BRA: { name: 'Brasil' },
	ARG: { name: 'Argentina' },
	URU: { name: 'Uruguai' },
	COL: { name: 'Colômbia' },
	ECU: { name: 'Equador' },
	PER: { name: 'Peru' },
	CHI: { name: 'Chile' },
	PAR: { name: 'Paraguai' },
	VEN: { name: 'Venezuela' },
	BOL: { name: 'Bolívia' },

	// UEFA
	GER: { name: 'Alemanha' },
	ESP: { name: 'Espanha' },
	FRA: { name: 'França' },
	ENG: { name: 'Inglaterra' },
	POR: { name: 'Portugal' },
	ITA: { name: 'Itália' },
	NED: { name: 'Holanda' },
	BEL: { name: 'Bélgica' },
	CRO: { name: 'Croácia' },
	DEN: { name: 'Dinamarca' },
	POL: { name: 'Polônia' },
	SUI: { name: 'Suíça' },
	SRB: { name: 'Sérvia' },
	WAL: { name: 'País de Gales', short: 'Gales' },
	SCO: { name: 'Escócia' },
	AUT: { name: 'Áustria' },
	TUR: { name: 'Turquia' },
	UKR: { name: 'Ucrânia' },
	CZE: { name: 'República Tcheca', short: 'Tchéquia' },
	SVK: { name: 'Eslováquia' },
	HUN: { name: 'Hungria' },
	ROU: { name: 'Romênia' },
	IRL: { name: 'Irlanda' },
	NIR: { name: 'Irlanda do Norte', short: 'Irl. Norte' },
	NOR: { name: 'Noruega' },
	SWE: { name: 'Suécia' },
	FIN: { name: 'Finlândia' },
	ISL: { name: 'Islândia' },
	GRE: { name: 'Grécia' },
	ALB: { name: 'Albânia' },
	BIH: { name: 'Bósnia e Herzegovina', short: 'Bósnia' },
	SVN: { name: 'Eslovênia' },
	GEO: { name: 'Geórgia' },
	ISR: { name: 'Israel' },
	RUS: { name: 'Rússia' },
	MKD: { name: 'Macedônia do Norte', short: 'Macedônia' },
	MNE: { name: 'Montenegro' },
	BUL: { name: 'Bulgária' },
	BLR: { name: 'Bielorrússia' },
	MDA: { name: 'Moldávia' },
	LUX: { name: 'Luxemburgo' },
	CYP: { name: 'Chipre' },
	ARM: { name: 'Armênia' },
	AZE: { name: 'Azerbaijão' },
	KOS: { name: 'Kosovo' },
	FRO: { name: 'Ilhas Faroé', short: 'Faroé' },
	GIB: { name: 'Gibraltar' },
	LIE: { name: 'Liechtenstein' },
	MLT: { name: 'Malta' },
	AND: { name: 'Andorra' },
	SMR: { name: 'San Marino' },
	EST: { name: 'Estônia' },
	LVA: { name: 'Letônia' },
	LTU: { name: 'Lituânia' },

	// CONCACAF
	USA: { name: 'Estados Unidos', short: 'EUA' },
	MEX: { name: 'México' },
	CAN: { name: 'Canadá' },
	CRC: { name: 'Costa Rica' },
	PAN: { name: 'Panamá' },
	HON: { name: 'Honduras' },
	GUA: { name: 'Guatemala' },
	SLV: { name: 'El Salvador' },
	HAI: { name: 'Haiti' },
	JAM: { name: 'Jamaica' },
	CUB: { name: 'Cuba' },
	TRI: { name: 'Trinidad e Tobago', short: 'Trinidad' },
	DOM: { name: 'República Dominicana', short: 'Rep. Dominicana' },
	NCA: { name: 'Nicarágua' },
	BLZ: { name: 'Belize' },
	SUR: { name: 'Suriname' },
	GUY: { name: 'Guiana' },
	CUW: { name: 'Curaçao' },

	// AFC
	JPN: { name: 'Japão' },
	KOR: { name: 'Coreia do Sul', short: 'Coreia' },
	PRK: { name: 'Coreia do Norte', short: 'Coreia N.' },
	AUS: { name: 'Austrália' },
	IRN: { name: 'Irã' },
	KSA: { name: 'Arábia Saudita', short: 'Arábia' },
	QAT: { name: 'Catar' },
	UAE: { name: 'Emirados Árabes Unidos', short: 'Emirados' },
	IRQ: { name: 'Iraque' },
	JOR: { name: 'Jordânia' },
	LBN: { name: 'Líbano' },
	SYR: { name: 'Síria' },
	OMA: { name: 'Omã' },
	BHR: { name: 'Bahrein' },
	KUW: { name: 'Kuwait' },
	YEM: { name: 'Iêmen' },
	PLE: { name: 'Palestina' },
	UZB: { name: 'Uzbequistão' },
	CHN: { name: 'China' },
	IND: { name: 'Índia' },
	IDN: { name: 'Indonésia' },
	THA: { name: 'Tailândia' },
	VIE: { name: 'Vietnã' },
	PHI: { name: 'Filipinas' },
	MAS: { name: 'Malásia' },
	SGP: { name: 'Cingapura' },
	TPE: { name: 'Taiwan' },
	TJK: { name: 'Tajiquistão' },
	TKM: { name: 'Turcomenistão' },
	KAZ: { name: 'Cazaquistão' },
	KGZ: { name: 'Quirguistão' },

	// CAF
	MAR: { name: 'Marrocos' },
	SEN: { name: 'Senegal' },
	TUN: { name: 'Tunísia' },
	EGY: { name: 'Egito' },
	NGA: { name: 'Nigéria' },
	GHA: { name: 'Gana' },
	CMR: { name: 'Camarões' },
	CIV: { name: 'Costa do Marfim', short: 'C. do Marfim' },
	ALG: { name: 'Argélia' },
	RSA: { name: 'África do Sul', short: 'África' },
	MLI: { name: 'Mali' },
	BFA: { name: 'Burkina Faso' },
	GUI: { name: 'Guiné' },
	GNB: { name: 'Guiné-Bissau' },
	GAB: { name: 'Gabão' },
	COD: { name: 'Rep. Dem. do Congo', short: 'Congo (RD)' },
	CGO: { name: 'Congo' },
	ANG: { name: 'Angola' },
	MOZ: { name: 'Moçambique' },
	ZIM: { name: 'Zimbábue' },
	ZAM: { name: 'Zâmbia' },
	KEN: { name: 'Quênia' },
	UGA: { name: 'Uganda' },
	TAN: { name: 'Tanzânia' },
	ETH: { name: 'Etiópia' },
	LBY: { name: 'Líbia' },
	SUD: { name: 'Sudão' },
	NAM: { name: 'Namíbia' },
	BOT: { name: 'Botswana' },
	CPV: { name: 'Cabo Verde' },
	MAD: { name: 'Madagascar' },
	MTN: { name: 'Mauritânia' },
	BEN: { name: 'Benin' },
	TOG: { name: 'Togo' },
	NIG: { name: 'Níger' },
	SLE: { name: 'Serra Leoa' },
	LBR: { name: 'Libéria' },
	GAM: { name: 'Gâmbia' },
	COM: { name: 'Comores' },
	MRI: { name: 'Maurício' },
	SEY: { name: 'Seychelles' },
	RWA: { name: 'Ruanda' },
	BDI: { name: 'Burundi' },
	SSD: { name: 'Sudão do Sul' },
	DJI: { name: 'Djibuti' },
	SOM: { name: 'Somália' },
	ERI: { name: 'Eritreia' },
	LES: { name: 'Lesoto' },
	SWZ: { name: 'Essuatíni' },
	MWI: { name: 'Maláui' },
	STP: { name: 'São Tomé e Príncipe', short: 'S. Tomé' },
	EQG: { name: 'Guiné Equatorial', short: 'Guiné Eq.' },
	CAF: { name: 'Rep. Centro-Africana', short: 'Centro-África' },
	CHA: { name: 'Chade' },

	// OFC
	NZL: { name: 'Nova Zelândia', short: 'N. Zelândia' },
	FIJ: { name: 'Fiji' },
	PNG: { name: 'Papua-Nova Guiné', short: 'Papua' },
	SOL: { name: 'Ilhas Salomão', short: 'Salomão' },
	VAN: { name: 'Vanuatu' },
	NCL: { name: 'Nova Caledônia', short: 'N. Caledônia' },
	TAH: { name: 'Taiti' },
	COK: { name: 'Ilhas Cook' },
	TGA: { name: 'Tonga' },
	SAM: { name: 'Samoa' },
	ASA: { name: 'Samoa Americana' },
}

export function teamName(team: Pick<TeamPayload, 'tla' | 'name'>): string {
	return PT_BY_TLA[team.tla]?.name ?? team.name
}

export function teamShortName(team: Pick<TeamPayload, 'tla' | 'name' | 'shortName'>): string {
	const pt = PT_BY_TLA[team.tla]
	if (pt) return pt.short ?? pt.name
	return team.shortName ?? team.name
}
